' ===============================================================================
' EXPORT MODULE - Advanced Export Functionality
' ===============================================================================
' File: VBA_ExportModule.bas
' Purpose: Comprehensive export functionality for PDF, Excel, CSV, and HTML
' ===============================================================================

Option Explicit

' ===============================================================================
' PDF EXPORT FUNCTIONS
' ===============================================================================

Sub PrepareForPDFExport()
    '
    ' Prepare sheets for PDF export - hide gridlines, adjust formatting
    '
    
    Dim ws As Worksheet
    
    For Each ws In ThisWorkbook.Worksheets
        With ws
            .DisplayGridlines = False
            .DisplayHeadings = False
            .PageSetup.PrintGridlines = False
            .PageSetup.PrintHeadings = False
            
            ' Set print area and page setup
            Call SetupPageForPDF(ws)
        End With
    Next ws
End Sub

Sub SetupPageForPDF(ws As Worksheet)
    '
    ' Setup individual sheet for PDF export
    '
    
    With ws.PageSetup
        .Orientation = xlPortrait
        .PaperSize = xlPaperA4
        .FitToPagesWide = 1
        .FitToPagesTall = False
        .Zoom = False
        
        ' Headers and footers
        .LeftHeader = "&L" & ws.Name
        .CenterHeader = "&C&B" & "CONSTRUCTION ESTIMATE"
        .RightHeader = "&R" & Format(Now, "dd-mmm-yyyy")
        
        .LeftFooter = "&L" & "Generated by Estimation System"
        .CenterFooter = ""
        .RightFooter = "&R" & "Page &P of &N"
        
        ' Margins
        .LeftMargin = Application.InchesToPoints(0.7)
        .RightMargin = Application.InchesToPoints(0.7)
        .TopMargin = Application.InchesToPoints(0.75)
        .BottomMargin = Application.InchesToPoints(0.75)
        .HeaderMargin = Application.InchesToPoints(0.3)
        .FooterMargin = Application.InchesToPoints(0.3)
    End With
    
    ' Auto-adjust orientation based on content width
    If ws.UsedRange.Columns.Count > 6 Then
        ws.PageSetup.Orientation = xlLandscape
    End If
End Sub

Sub ExportSheetsToPDF(filePath As String, projectName As String)
    '
    ' Export all sheets to single PDF in correct order
    '
    
    Dim sheetsToExport As Collection
    Dim ws As Worksheet
    Dim i As Integer
    
    Set sheetsToExport = New Collection
    
    ' Add General Abstract first
    If SheetExists("General Abstract") Then
        sheetsToExport.Add ThisWorkbook.Worksheets("General Abstract")
    End If
    
    ' Add Abstract and Measurement pairs
    For Each ws In ThisWorkbook.Worksheets
        If InStr(1, ws.Name, "Abstract of Cost", vbTextCompare) > 0 And _
           ws.Name <> "General Abstract" Then
            sheetsToExport.Add ws
            
            ' Add corresponding measurement sheet
            Dim measurementName As String
            measurementName = Replace(ws.Name, "Abstract of Cost", "Measurement")
            If SheetExists(measurementName) Then
                sheetsToExport.Add ThisWorkbook.Worksheets(measurementName)
            End If
        End If
    Next ws
    
    ' Export to PDF
    If sheetsToExport.Count > 0 Then
        Dim sheetArray() As String
        ReDim sheetArray(1 To sheetsToExport.Count)
        
        For i = 1 To sheetsToExport.Count
            sheetArray(i) = sheetsToExport(i).Name
        Next i
        
        ThisWorkbook.Worksheets(sheetArray).ExportAsFixedFormat _
            Type:=xlTypePDF, _
            Filename:=filePath, _
            Quality:=xlQualityStandard, _
            IncludeDocProps:=True, _
            IgnorePrintAreas:=False, _
            OpenAfterPublish:=True
    End If
End Sub

Sub RestoreAfterPDFExport()
    '
    ' Restore original formatting after PDF export
    '
    
    Dim ws As Worksheet
    
    For Each ws In ThisWorkbook.Worksheets
        ws.DisplayGridlines = True
        ws.DisplayHeadings = True
    Next ws
End Sub

' ===============================================================================
' EXCEL EXPORT FUNCTIONS
' ===============================================================================

Sub RemoveProtectionFromWorkbook(wb As Workbook)
    '
    ' Remove protection from all sheets in workbook
    '
    
    Dim ws As Worksheet
    
    For Each ws In wb.Worksheets
        ws.Unprotect Password:="estimation2025"
        ws.Cells.Locked = False
    Next ws
End Sub

Sub CreateExportLog(wb As Workbook, exportType As String, filePath As String)
    '
    ' Create export log in hidden sheet
    '
    
    Dim logWs As Worksheet
    Dim lastRow As Long
    
    ' Create or get log sheet
    On Error Resume Next
    Set logWs = wb.Worksheets("Export_Log")
    On Error GoTo 0
    
    If logWs Is Nothing Then
        Set logWs = wb.Worksheets.Add
        logWs.Name = "Export_Log"
        logWs.Visible = xlSheetVeryHidden
        
        ' Setup headers
        logWs.Range("A1").Value = "Timestamp"
        logWs.Range("B1").Value = "Export Type"
        logWs.Range("C1").Value = "User"
        logWs.Range("D1").Value = "File Path"
        logWs.Range("A1:D1").Font.Bold = True
    End If
    
    ' Add log entry
    lastRow = logWs.Cells(logWs.Rows.Count, 1).End(xlUp).Row + 1
    logWs.Cells(lastRow, 1).Value = Now
    logWs.Cells(lastRow, 2).Value = exportType
    logWs.Cells(lastRow, 3).Value = Application.UserName
    logWs.Cells(lastRow, 4).Value = filePath
End Sub

' ===============================================================================
' CSV EXPORT FUNCTIONS
' ===============================================================================

Sub ExportToCSVPackage()
    '
    ' Export all sheets as CSV files in a zip package
    '
    
    Dim folderPath As String
    Dim ws As Worksheet
    Dim csvPath As String
    
    ' Get folder path
    folderPath = Application.GetSaveAsFilename( _
        InitialFilename:="EstimateCSV", _
        FileFilter:="Folders,", _
        Title:="Select folder for CSV export")
    
    If folderPath = "False" Then Exit Sub
    
    ' Create folder if not exists
    folderPath = Left(folderPath, InStrRev(folderPath, "\")) & "EstimateCSV_" & Format(Now, "yyyymmdd_hhmmss")
    MkDir folderPath
    
    Application.ScreenUpdating = False
    
    ' Export each sheet as CSV
    For Each ws In ThisWorkbook.Worksheets
        csvPath = folderPath & "\" & CleanFileName(ws.Name) & ".csv"
        Call ExportSheetToCSV(ws, csvPath)
    Next ws
    
    Application.ScreenUpdating = True
    
    MsgBox "CSV files exported to: " & folderPath, vbInformation, "Export Complete"
End Sub

Sub ExportSheetToCSV(ws As Worksheet, filePath As String)
    '
    ' Export single sheet to CSV
    '
    
    Dim tempWb As Workbook
    Dim tempWs As Worksheet
    
    ' Create temporary workbook
    Set tempWb = Workbooks.Add
    Set tempWs = tempWb.Worksheets(1)
    
    ' Copy data
    ws.UsedRange.Copy tempWs.Range("A1")
    
    ' Save as CSV
    Application.DisplayAlerts = False
    tempWb.SaveAs filePath, FileFormat:=xlCSV
    tempWb.Close False
    Application.DisplayAlerts = True
End Sub

Function CleanFileName(fileName As String) As String
    '
    ' Clean filename for file system compatibility
    '
    
    Dim invalidChars As String
    Dim i As Integer
    
    invalidChars = "\/:*?""<>|"
    
    For i = 1 To Len(invalidChars)
        fileName = Replace(fileName, Mid(invalidChars, i, 1), "_")
    Next i
    
    CleanFileName = fileName
End Function

' ===============================================================================
' HTML EXPORT FUNCTIONS
' ===============================================================================

Sub ExportToPrintableHTML()
    '
    ' Export estimate as printable HTML
    '
    
    Dim filePath As String
    Dim htmlContent As String
    Dim fileNum As Integer
    
    filePath = Application.GetSaveAsFilename( _
        FileFilter:="HTML Files (*.html), *.html", _
        Title:="Export to HTML")
    
    If filePath = "False" Then Exit Sub
    
    ' Generate HTML content
    htmlContent = GenerateHTMLContent()
    
    ' Write to file
    fileNum = FreeFile
    Open filePath For Output As fileNum
    Print #fileNum, htmlContent
    Close fileNum
    
    MsgBox "HTML file created successfully!", vbInformation, "Export Complete"
End Sub

Function GenerateHTMLContent() As String
    '
    ' Generate complete HTML content for all sheets
    '
    
    Dim html As String
    Dim ws As Worksheet
    
    ' HTML header
    html = "<!DOCTYPE html>" & vbCrLf & _
           "<html><head>" & vbCrLf & _
           "<title>Construction Estimate</title>" & vbCrLf & _
           "<style>" & vbCrLf & _
           GetHTMLStyles() & vbCrLf & _
           "</style></head><body>" & vbCrLf & _
           "<h1>Construction Estimate Report</h1>" & vbCrLf & _
           "<p>Generated on: " & Format(Now, "dd-mmm-yyyy hh:mm") & "</p>" & vbCrLf
    
    ' Add each sheet
    For Each ws In ThisWorkbook.Worksheets
        html = html & GenerateSheetHTML(ws) & vbCrLf
    Next ws
    
    ' HTML footer
    html = html & "</body></html>"
    
    GenerateHTMLContent = html
End Function

Function GetHTMLStyles() As String
    '
    ' Get CSS styles for HTML export
    '
    
    GetHTMLStyles = _
        "body { font-family: Arial, sans-serif; margin: 20px; }" & vbCrLf & _
        "table { border-collapse: collapse; width: 100%; margin-bottom: 30px; }" & vbCrLf & _
        "th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }" & vbCrLf & _
        "th { background-color: #f2f2f2; font-weight: bold; }" & vbCrLf & _
        "h2 { color: #333; border-bottom: 2px solid #333; }" & vbCrLf & _
        ".number { text-align: right; }" & vbCrLf & _
        "@media print { body { margin: 0; } table { page-break-inside: avoid; } }"
End Function

Function GenerateSheetHTML(ws As Worksheet) As String
    '
    ' Generate HTML table for a single sheet
    '
    
    Dim html As String
    Dim lastRow As Long, lastCol As Long
    Dim r As Long, c As Long
    Dim cellValue As String
    
    html = "<h2>" & ws.Name & "</h2>" & vbCrLf & "<table>" & vbCrLf
    
    lastRow = ws.UsedRange.Rows.Count
    lastCol = ws.UsedRange.Columns.Count
    
    For r = 1 To lastRow
        html = html & "<tr>"
        
        For c = 1 To lastCol
            cellValue = ws.Cells(r, c).Value
            If IsNumeric(cellValue) And cellValue <> "" Then
                html = html & "<td class='number'>" & Format(cellValue, "#,##0.00") & "</td>"
            Else
                html = html & "<td>" & cellValue & "</td>"
            End If
        Next c
        
        html = html & "</tr>" & vbCrLf
    Next r
    
    html = html & "</table>" & vbCrLf
    
    GenerateSheetHTML = html
End Function

' ===============================================================================
' PROGRESS INDICATOR
' ===============================================================================

Sub ShowProgressIndicator(message As String, percent As Integer)
    '
    ' Show progress indicator for long operations
    '
    
    Application.StatusBar = message & " (" & percent & "%)"
    DoEvents
End Sub

Sub HideProgressIndicator()
    '
    ' Hide progress indicator
    '
    
    Application.StatusBar = False
End Sub